### ISSUE TITLE
Different push pin for markers with images or comments

### ISSUE THREAD

**Issue by xZise** [espinosaluis/TrackMeViewer#10]
As in mentioned in #9, pushpins could be different if the marker has comments or images associated with it.

**Comment by xZise** [comment]
As I don't use the phone client I don't really know how it looks there but one issue could be that the direction is then not visible. So it probably needs to be an option.

But judging from the code it seems possible. Unfortunately I have a lot of patches in the queue and especially later ones will make the design different on how to choose the icon. So at some point this could be implemented.

**Comment by espinosaluis** [comment]
Yes, that's working ok. If you click on "Show Config", and then check "Display bearing arrows" they will appear.

**Comment by xZise** [comment]
I know but that is not what I meant. I meant that when the bearing arrows are used, should that hide the “image”/“comment” markers, so that these special markers are only shown when the bearing arrows are disabled and the gray markers are used.

Also what should happen to the green (start) and red (end) markers? And is there some way to get the file used in the app? Please note that this repository is licensed using the MIT License and I don't know under which licenses the apps are.

**Comment by espinosaluis** [comment]
I see. Yes, not showing the icons in a different color is ok when the arrows are present or there is a green or start marker.
By the way, I just tried the viewer again and I still cannot see the icons with a comment in a different color.

**Comment by xZise** [comment]
Ehm I haven't provided a patch yet to see them in a different color?

**Comment by espinosaluis** [comment]
Sorry, I missed your previous comment... I read too fast.

**Comment by xZise** [comment]
Okay there is the yellow marker which I now use in a future patch. I need to look through the patches to determine when to introduce it so it can be introduced as soon as possible.

**Comment by xZise** [comment]
This should be implemented now as these markers will be highlighted with yellow. Feel free to open it again if you found issues or see improvements.

**Comment by xZise** [comment]
Well that patch has been wiped out so open it becomes.

**Comment by xZise** [comment]
Okay #38 has implemented that feature.
