### ISSUE TITLE
Trip deletion does not check if the user is logged in

### ISSUE THREAD

**Issue by xZise** [espinosaluis/TrackMeViewer#3]
Opening a TrackMeViewer instance and adding `?deleteTrip=42` suffices to delete that trip. It does not verify whether the user is actually logged in.

**Comment by espinosaluis** [comment]
Thanks for noticing that. It seems that was one of the latest additions by the community and they forgot to do that. Unfortunately I don't remember the person who did that so I can ask him to fix it.
I do verify it when deleting trips from the phone though.

**Comment by xZise** [comment]
Yes `requests.php` is afaik used by the client and that is requiring that the user is logged in.

Anyway this is a glaring security issue in the current master and depending on how you want to handle you could remove the related parts and that removal could be reverted if the system is more improved to actually check if the user is logged in.

**Comment by espinosaluis** [comment]
I checked the requests.php file and on top of the file, it checks that you have specified a username and password, so unless I'm wrong, it looks ok to me.

**Comment by espinosaluis** [comment]
_Comment deleted_
Again, I read too fast... the problem is on the viewer, not the requests.php file.

**Comment by xZise** [comment]
Okay I have a patch for that ready but it unfortunately needs #45 as there are error messages which need to be translated (and the current system does not allow a fallback language).
