### ISSUE TITLE
You need to logout if you happen to close the viewer

### ISSUE THREAD

**Issue by espinosaluis** [espinosaluis/TrackMeViewer#30]
Once you have logged in, if you close the page and go back to the viewer, it won't remember that you are logged in and an empty map is shown and the user information is missing. Check attached image.

![capture](https://cloud.githubusercontent.com/assets/12634078/11659626/816232b4-9dc9-11e5-8df7-a870b06456ab.PNG)

**Comment by xZise** [comment]
Okay the issue is that my patch isn't actually extracting the ID from the session variable.

**Comment by xZise** [comment]
Okay actually found the place where the regression happened and also wrote a patch for that issue.
