### ISSUE TITLE
Feature request: Remove option 'Any' from the web viewer

### ISSUE THREAD

**Issue by espinosaluis** [espinosaluis/TrackMeViewer#92]
By selecting this option it will show ALL the positions for ALL the routes. 
After using TrackMe for more than 10 years, this will be too much to display.

**Comment by OpitZle** [comment]
With v 3.5 there is a way to group the trips into different groups. Given this, the [Any] opions makes good sense (e.g. see all trips from a certain holiday week together).
Therefore the [Any] options will stay. 
Note: The [None] options is removed in v3.5
